name: squaregrammer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  color: ^2.1.1
  image_picker: ^0.5.0
  image: ^2.0.6



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
